# Autogenerated wrapper script for Libical_jll for i686-w64-mingw32-cxx11
export libical, libical_cxx, libicalss, libicalss_cxx, libicalvcal

using BerkeleyDB_jll
using Glib_jll
using ICU_jll
using XML2_jll
JLLWrappers.@generate_wrapper_header("Libical")
JLLWrappers.@declare_library_product(libical, "libical.dll")
JLLWrappers.@declare_library_product(libical_cxx, "libical_cxx.dll")
JLLWrappers.@declare_library_product(libicalss, "libicalss.dll")
JLLWrappers.@declare_library_product(libicalss_cxx, "libicalss_cxx.dll")
JLLWrappers.@declare_library_product(libicalvcal, "libicalvcal.dll")
function __init__()
    JLLWrappers.@generate_init_header(BerkeleyDB_jll, Glib_jll, ICU_jll, XML2_jll)
    JLLWrappers.@init_library_product(
        libical,
        "bin\\libical.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libical_cxx,
        "bin\\libical_cxx.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicalss,
        "bin\\libicalss.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicalss_cxx,
        "bin\\libicalss_cxx.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicalvcal,
        "bin\\libicalvcal.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
