# Autogenerated wrapper script for Libical_jll for x86_64-apple-darwin
export libical, libical_cxx, libicalss, libicalss_cxx, libicalvcal

using BerkeleyDB_jll
using Glib_jll
using ICU_jll
using XML2_jll
JLLWrappers.@generate_wrapper_header("Libical")
JLLWrappers.@declare_library_product(libical, "@rpath/libical.3.dylib")
JLLWrappers.@declare_library_product(libical_cxx, "@rpath/libical_cxx.3.dylib")
JLLWrappers.@declare_library_product(libicalss, "@rpath/libicalss.3.dylib")
JLLWrappers.@declare_library_product(libicalss_cxx, "@rpath/libicalss_cxx.3.dylib")
JLLWrappers.@declare_library_product(libicalvcal, "@rpath/libicalvcal.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(BerkeleyDB_jll, Glib_jll, ICU_jll, XML2_jll)
    JLLWrappers.@init_library_product(
        libical,
        "lib/libical.3.0.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libical_cxx,
        "lib/libical_cxx.3.0.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicalss,
        "lib/libicalss.3.0.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicalss_cxx,
        "lib/libicalss_cxx.3.0.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicalvcal,
        "lib/libicalvcal.3.0.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
